service: "aws-template-ts"

plugins:
  - serverless-esbuild
  - serverless-offline

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${sls:stage}
  region: us-east-1
  deploymentBucket:
    name: ${env:BUCKET_S3_NAME} # serverless-${self:service}-${sls:stage}
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - "lambda:*"
          Resource: "*"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!node_modules/**"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

functions:
  - ${file(src/samples/application/serverless/events.yml)}
  - ${file(src/users/application/serverless/events.yml)}