service: "AWSTEMPLATETS"

plugins:
  - serverless-esbuild
  - serverless-offline

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: ${env:AWS_RUNTIME}
  stage: ${sls:stage}
  region: ${env:AWS_REGION}
  timeout: ${env:SLS_TIMEOUT} # Por defecto es 3 segundos, establecer a 30 para un correcto debug

  # AWS Bucket S3
  deploymentBucket:
    name: ${env:AWS_BUCKET_S3_NAME} # serverless-${self:service}-${sls:stage}
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

  # AWS IAM
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:*"
          Resource: "*"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!node_modules/**"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

# layers:
#   base:
#     name: "app-dependencies"
#     compatibleArchitectures:
#       - "nodejs18.x"
#     package:
#       artifact: "app.zip"

functions:
  - ${file(src/samples/application/serverless/events.yaml)}
  - ${file(src/users/application/serverless/events.yaml)}
